CREATE TABLE IF NOT EXISTS USERS(
	EMAIL VARCHAR(100),
	PASSWORD VARCHAR(10000) NOT NULL,
	ANALIST BOOL,
	CONSTRAINT pk_users_email PRIMARY KEY (EMAIL)
);

CREATE TABLE IF NOT EXISTS INTERNS(
	EMAIL VARCHAR(100),
	FULLNAME VARCHAR(200) NOT NULL,
	DEGREE VARCHAR(100) NOT NULL,
	SEMESTER INTEGER,
	CV_ROUTE VARCHAR(500),
	CONSTRAINT pk_interns_email PRIMARY KEY (EMAIL),
	CONSTRAINT fk_interns_email FOREIGN KEY (EMAIL) REFERENCES USERS(EMAIL)
)